export const Emblemas: Record<string, any> = {
  PAL: require("../assets/emblemas/palmeiras.svg"),
  FLA: require("../assets/emblemas/flamengo.svg"),
  COR: require("../assets/emblemas/corinthians.svg"),
  SAO: require("../assets/emblemas/sao_paulo.svg"),
  SAN: require("../assets/emblemas/santos.svg"),
  VAS: require("../assets/emblemas/vasco.svg"),
  BOT: require("../assets/emblemas/botafogo.svg"),
  CAM: require("../assets/emblemas/atletico_mineiro.svg"),
  CRU: require("../assets/emblemas/cruzeiro.svg"),
  INT: require("../assets/emblemas/internacional.svg"),
  GRE: require("../assets/emblemas/gremio.svg"),
  BAH: require("../assets/emblemas/bahia.svg"),
  CEA: require("../assets/emblemas/ceara.svg"),
  FOR: require("../assets/emblemas/fortaleza.svg"),
  CAP: require("../assets/emblemas/paranaense.svg"),
  CFC: require("../assets/emblemas/coritiba.svg"),
  VIT: require("../assets/emblemas/vitoria.svg"),
  CHA: require("../assets/emblemas/chapecoense.svg"),
  SPO: require("../assets/emblemas/sport-recife.svg"),
  SAM: require("../assets/emblemas/sampaio.svg"),
};
